import numpy as np

print('Tablica z 10 zerami')
zeros = np.zeros(10)
print(zeros)

print('Tablica z 10 piątkami')
fives = np.full(10, 5)
print(fives)

print('Tablica zawierająca liczby od 10 do 50')
fifty_range = np.arange(10, 51, 1)
print(fifty_range)

print('Macierz 3x3 zawierająca liczby od 0 do 8')
nine_range = np.arange(9).reshape(3, 3)
print(nine_range)

print('Macierz jednostkowa 3x3')
eye_matrix = np.eye(3)
print(eye_matrix)

print('Macierz 5x5 zawierająca liczby z dystrybucji normalnej (Gaussa)')
gauss_matrix_size = (5, 5)
gauss_matrix = np.random.normal(size=gauss_matrix_size)
print(gauss_matrix)

print('Macierz 10x10 zawierająca liczby od 0.01 do 1.0')
ten_matrix = np.arange(0.0, 1.0, 0.01).reshape(10, 10)
print(ten_matrix)

print('Tablica zawierająca 20 liniono rozłożonych liczb między 0 a 1')
lin_array = np.linspace(0, 1, 20)
print(lin_array)

print('Macierz 5x5 zawierająca losowe liczby z przedziału (1,25)')
random_array = np.random.random_integers(1, 25, 25)
first_random_matrix = random_array.reshape((5, 5))
print(first_random_matrix)

print('Suma wszystkich liczb w macierzy')
sum = first_random_matrix.sum()
print(sum)
print('Średnia wszystkich liczb w macierzy')
mean = first_random_matrix.mean()
print(mean)
print('Dewiacja standardowa liczb w macierzy')
deviation = first_random_matrix.std()
print(deviation)
print('Suma liczb w każdej kolumnie macierzy')
cumsum = first_random_matrix.sum(axis=0)
print(cumsum)

print('Macierz 5x5 zawierająca losowe liczby z przedziału (0,100)')
second_random_matrix = np.random.random_integers(0, 100, (5, 5))
print(second_random_matrix)

print('Mediana liczb macierzy')
median = np.median(second_random_matrix)
print(median)
print('Najmniejsza liczba macierzy')
min = np.min(second_random_matrix)
print(min)
print('Największa liczba macierzy')
max = np.max(second_random_matrix)
print(max)

print('Macierz 2x4 z losowymi liczbami z przedziału (0,100)')
third_random_matrix = np.random.random_integers(0, 100, (2, 4))
print(third_random_matrix)
print('Macierz po transpozycji')
transposed = third_random_matrix.transpose()
print(transposed)

print('Dwie macierze i ich suma')
first_matrix = np.random.random_integers(0, 15, (3, 4))
second_matrix = np.random.random_integers(0, 15, (3, 4))
sum_matrix = np.add(first_matrix, second_matrix)
print(first_matrix)
print(second_matrix)
print(sum_matrix)

print('Dwie macierze')
third_matrix = np.random.random_integers(10, 50, (5, 6))
fourth_matrix = np.random.random_integers(10, 50, (6, 5))
print(third_matrix)
print(fourth_matrix)
print('Iloczyny tych macierzy')
first_multiply = np.dot(third_matrix, fourth_matrix)
second_multiply = np.matmul(third_matrix, fourth_matrix)
print(first_multiply)
print(second_multiply)